# Generated by Django 6.0.1 on 2026-02-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name from lucide-react (e.g., 'Package', 'Printer')", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price in AED', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True)),
                ('discount', models.IntegerField(default=0, help_text='Discount percentage (0-100)')),
                ('stock_count', models.IntegerField(default=0, help_text='Available quantity')),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(help_text='Main product description')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features: ["Feature 1", "Feature 2"]', null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Specifications: {"Weight": "1kg", "Color": "Black"}')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, help_text='Average rating (0.0 - 5.0)', max_digits=3)),
                ('reviews', models.IntegerField(default=0, help_text='Number of reviews')),
                ('main_image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Is product visible?')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('icon', models.CharField(blank=True, help_text='Icon name from lucide-react', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(help_text='Product subcategory', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.subcategory'),
        ),
    ]
