# Generated by Django 6.0.1 on 2026-02-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['navbar_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='navbar_order',
            field=models.IntegerField(default=0, help_text='Display order in navbar (1, 2, 3, etc.). 0 = not shown'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_navbar',
            field=models.BooleanField(default=False, help_text='Display this category in the navigation bar'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('new', 'New Product'), ('refurbished', 'Refurbished Product'), ('rental', 'Rental Product')], default='new', help_text='Select product type: New, Refurbished, or Rental', max_length=20),
        ),
    ]
