# Generated by Django 6.0.1 on 2026-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features: ["Feature 1", "Feature 2"]', null=True),
        ),
    ]
