# Generated by Django 6.0.1 on 2026-02-14 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_navbar_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, help_text='Product condition (e.g., Excellent, Good, Fair for refurbished items)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (leave blank to use product name)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='min_rental_period',
            field=models.IntegerField(blank=True, help_text='Minimum rental period in days', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_daily',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rental price in AED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental price in AED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_weekly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly rental price in AED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.IntegerField(blank=True, help_text='Warranty period in months', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, help_text='Average rating (0.0 - 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(default=0, help_text='Number of reviews', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0, help_text='Available quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_navbar', 'navbar_order'], name='products_ca_show_in_f252df_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'is_active'], name='products_pr_subcate_65f48e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='products_pr_is_feat_a1ecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock'], name='products_pr_in_stoc_4fee1a_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='products_pr_product_e55bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'is_active'], name='products_su_categor_86a9be_idx'),
        ),
    ]
